# Generated by Django 5.1.4 on 2024-12-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prefered_genres',
            new_name='preferred_genres',
        ),
    ]
