# Generated by Django 5.1.4 on 2024-12-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0011_remove_book_average_rating_remove_book_ratings_sum_and_more'),
        ('users', '0004_rename_prefered_genres_user_preferred_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='want_to_read_books',
            field=models.ManyToManyField(related_name='want_to_read', to='books_database.book'),
        ),
    ]
