# Generated by Django 5.1.4 on 2025-01-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_want_to_read_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
