# Generated by Django 5.1.4 on 2025-01-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='want_to_read_books',
        ),
    ]
