# Generated by Django 5.1.4 on 2025-01-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_want_to_read_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='currently_reading_books',
        ),
    ]
