# Generated by Django 5.1.4 on 2025-02-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_level_remove_user_xp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followrelation',
            options={'verbose_name_plural': 'Follow Relations'},
        ),
    ]
