# Generated by Django 5.1.4 on 2024-12-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0006_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
