# Generated by Django 5.1.4 on 2024-12-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0008_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='default', null=True, unique=True),
        ),
    ]
