# Generated by Django 5.1.4 on 2024-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0009_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='default', null=True),
        ),
    ]
