# Generated by Django 5.1.4 on 2024-12-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0010_alter_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_sum',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_reviews',
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
