# Generated by Django 5.1.4 on 2025-01-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0011_remove_book_average_rating_remove_book_ratings_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='No description', max_length=500),
        ),
    ]
