# Generated by Django 5.1.4 on 2025-01-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0012_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='No description', max_length=1000),
        ),
    ]
