# Generated by Django 5.1.4 on 2025-02-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0015_currentlyreadingbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoreadbook',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
