# Generated by Django 5.1.4 on 2025-02-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0018_alter_bookreview_review_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'verbose_name_plural': 'Book Reviews'},
        ),
        migrations.AlterModelOptions(
            name='currentlyreadingbook',
            options={'verbose_name_plural': 'Currently Reading Books'},
        ),
        migrations.AlterModelOptions(
            name='readbook',
            options={'verbose_name_plural': 'Read Books'},
        ),
        migrations.AlterModelOptions(
            name='wanttoreadbook',
            options={'verbose_name_plural': 'Want To Read Books'},
        ),
    ]
