# Generated by Django 5.1.4 on 2025-02-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0019_alter_bookreview_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readbook',
            old_name='read_date',
            new_name='date',
        ),
    ]
