# Generated by Django 5.1.4 on 2025-02-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0022_rename_add_date_currentlyreadingbook_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanttoreadbook',
            old_name='add_date',
            new_name='date',
        ),
    ]
