# Generated by Django 5.1.4 on 2025-02-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_database', '0023_rename_add_date_wanttoreadbook_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='review_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='bookreview',
            old_name='review_user',
            new_name='user',
        ),
    ]
