# Generated by Django 5.1.4 on 2025-01-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followactivity',
            options={'verbose_name_plural': 'Follow Activities'},
        ),
    ]
