# Generated by Django 5.1.4 on 2025-01-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_followactivity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentlyreadingactivity',
            options={'verbose_name_plural': 'Currently Reading Activities'},
        ),
        migrations.AlterModelOptions(
            name='readactivity',
            options={'verbose_name_plural': 'Read Activities'},
        ),
        migrations.AlterModelOptions(
            name='wanttoreadactivity',
            options={'verbose_name_plural': 'Want To Read Activities'},
        ),
    ]
