# Generated by Django 5.1.4 on 2025-02-07 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_remove_currentlyreadingactivity_polymorphic_ctype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_reading_activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activities.currentlyreadingactivity')),
                ('follow_activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activities.followactivity')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating_activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activities.ratingactivity')),
                ('read_activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activities.readactivity')),
                ('want_to_read_activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activities.wanttoreadactivity')),
            ],
        ),
    ]
