# Generated by Django 5.1.4 on 2025-02-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activitywrapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitywrapper',
            name='currently_reading_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.currentlyreadingactivity'),
        ),
        migrations.AlterField(
            model_name='activitywrapper',
            name='follow_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.followactivity'),
        ),
        migrations.AlterField(
            model_name='activitywrapper',
            name='rating_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.ratingactivity'),
        ),
        migrations.AlterField(
            model_name='activitywrapper',
            name='read_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.readactivity'),
        ),
        migrations.AlterField(
            model_name='activitywrapper',
            name='want_to_read_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.wanttoreadactivity'),
        ),
    ]
