# Generated by Django 5.1.4 on 2025-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activitywrapper_currently_reading_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitywrapper',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
