# Generated by Django 5.1.4 on 2025-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activitywrapper_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyreadingactivity',
            name='activity_datetime',
        ),
        migrations.RemoveField(
            model_name='followactivity',
            name='activity_datetime',
        ),
        migrations.RemoveField(
            model_name='ratingactivity',
            name='activity_datetime',
        ),
        migrations.RemoveField(
            model_name='readactivity',
            name='activity_datetime',
        ),
        migrations.RemoveField(
            model_name='wanttoreadactivity',
            name='activity_datetime',
        ),
        migrations.AlterField(
            model_name='activitywrapper',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
