# Generated by Django 5.1.4 on 2025-02-10 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_remove_currentlyreadingactivity_activity_datetime_and_more'),
        ('forum', '0009_rename_content_post_caption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewThreadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_%(class)s', to='forum.thread')),
            ],
            options={
                'verbose_name_plural': 'New Thread Activities',
            },
        ),
        migrations.AddField(
            model_name='activitywrapper',
            name='new_thread_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.newthreadactivity'),
        ),
    ]
