# Generated by Django 5.1.4 on 2025-02-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_likeactivity_activitywrapper_like_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitywrapper',
            options={'verbose_name_plural': 'Activity Wrappers'},
        ),
    ]
